### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Resoluciones** [gigaherz/NotOnMyLawn#3]
Hi!  Congratulations for this plugin!

Would it be possible to update this plugin?  It is not blocking custom spawn event.

Thanks!!!!

**Comment by gigaherz** [comment]
Hello, I haven't worked on this plugin in almost 6 years, and I'm not really interested in updating it. I wrote it for a small server I had with some friends, that stopped existing shortly after I released this.

I don't mind if someone else wants to fork this code and bring it up to date, the license clearly allows it.

I'll take this chance to set this repository as an Archive, so it's more clear that I'm no longer interested in continuing.

Thanks for your interest.
